
# Basis-URL für die OpenAI-Kompatible REST-API von Google Gemini
# (Gemini hat aber auch eine eigene REST-API, die hier aber nicht verwendet wird).
sentimentanalyse.basisurl=https://generativelanguage.googleapis.com

# Pfad, der an Basis-URL angehängt wird
sentimentanalyse.pfad=/v1beta/openai/chat/completions

# Technischer Name des KI-Modells (LLM), das für die Sentimentanalyse verwendet werden soll.
sentimentanalyse.model=gemini-3.1-flash-lite

# Geheimer API-Key für die Authentifizierung bei der REST-API.
sentimentanalyse.apikey=HIER_EINTRAGEN
