
spring.application.name=Sentimentanalyse

# Für die Klasse RestClient musste in der pom.xml die Abhängigkeit
# "spring-boot-starter-webmvc" hinzugefügt werden, aber da diese
# Abhängigkeit die automatische Konfiguration für eine Webanwendung
# aktiviert, muss hier explizit angegeben werden, dass es sich um
# keine Webanwendung handelt.
spring.main.web-application-type=none